### ISSUE TITLE
Help key redirects to a non-accessible webpage

### ISSUE THREAD

**Issue by amber-libby** [RITAccess/blockly#13] opened 2015-06-23 19:46 UTC
The help key brings up information on each type block in a new webpage. Click on a block and then use the correctly designated hot key. Some of the webpages that are used are github and wikipedia. Neither of these are accessible. Pages that are accessible with short concise information about the blocks would be better to link to.

**Comment by amber-libby** [comment] 2015-07-01 15:43
We have made a Quick Reference Guide that will be linked to instead of wikipedia/Github. There are pages for each category of blocks as well as a homepage and soon to be a key strokes information page too. The anchor tags that will be used to link to the correct spot on the page are equivalent to the "type" of the block. The type of block is an attribute in the XML.

**Comment by amber-libby** [comment] 2015-07-06 21:03
Block descriptions are complete and the resource is put together. The homepage needs a better/more accurate description and the hotkeys pages needs to be filled in with content.

**Comment by MaryS94** [comment] 2015-07-17 18:40
Since the quick ref is made and this issue is a duplicate of "help URL of each block needs to be corrected"  Im going to close it.

**Closed by MaryS94** 2015-07-17 18:40 UTC
